const XP_TIERS={micro:{name:'微行动',xp:10},standard:{name:'标准',xp:20},training:{name:'训练',xp:40},challenge:{name:'挑战',xp:60}};
const ATTRS={strength:{name:'力量'},vitality:{name:'生命'},wisdom:{name:'智慧'},charm:{name:'魅力'}};
const GROUPS={strength:'力量训练',vitality:'生命维护',charm:'魅力维护'};
const SIDE_META={reading:{name:'阅读'},movie:{name:'观影'},learning:{name:'学习'}};
const SEED_TASKS=[
 {id:'bike',title:'健身单车',detail:'完成 30 分钟有氧',tier:'training',attr:'strength',boss:true,active:true,mark:'BIKE'},
 {id:'rower',title:'划船机',detail:'完成 30 分钟有氧',tier:'training',attr:'strength',boss:true,active:true,mark:'ROW'},
 {id:'breakfast',title:'早餐补给',detail:'麦片与牛奶',tier:'micro',attr:'vitality',boss:false,active:true,mark:'MEAL'},
 {id:'vitamin',title:'维生素 / 服药',detail:'按今日计划执行',tier:'standard',attr:'vitality',boss:false,active:true,mark:'MED'},
 {id:'footcare',title:'脚伤涂药护理',detail:'记录恢复情况',tier:'standard',attr:'vitality',boss:false,active:true,mark:'CARE'},
 {id:'cleanse',title:'洗脸与基础护肤',detail:'清洁、护肤、乳液',tier:'standard',attr:'charm',boss:false,active:true,mark:'SKIN'},
 {id:'device',title:'瘦脸仪护理',detail:'完成今日护理流程',tier:'standard',attr:'charm',boss:false,active:true,mark:'FACE'}
];
const DEFAULT={version:2,totalXp:0,tasks:SEED_TASKS,completed:{},sideLogs:[],weightLost:0,streak:0,attributes:{strength:0,vitality:0,wisdom:0,charm:0},boss:{goalJin:15,currentLost:0,bestLost:0,weightLogs:[],milestonesAwarded:[]}};
const dayKey=(date=new Date())=>date.toLocaleDateString('sv-SE');
const clone=value=>JSON.parse(JSON.stringify(value));
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let state=loadState();let currentPage='home';
const motionReduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
let characterBlinking=false;

function normalizeTask(task,index){const tier=task.tier||(task.xp>=60?'challenge':task.xp>=40?'training':task.xp<=10?'micro':'standard');const attr=['strength','vitality','charm'].includes(task.attr)?task.attr:'vitality';return {...task,id:task.id||`task-${Date.now()}-${index}`,tier,attr,boss:Boolean(task.boss),active:task.active!==false,mark:task.mark||ATTRS[attr].name.slice(0,1)}}
function loadState(){try{const saved=JSON.parse(localStorage.getItem('xusheng-state')||'{}'),next={...clone(DEFAULT),...saved};next.attributes={...DEFAULT.attributes,...saved.attributes};next.tasks=(saved.tasks?.length?saved.tasks:SEED_TASKS).map(normalizeTask);const oldLost=Number(saved.weightLost)||0;next.boss={...DEFAULT.boss,...saved.boss};next.boss.currentLost=Number(next.boss.currentLost||oldLost)||0;next.boss.bestLost=Math.max(Number(next.boss.bestLost)||0,oldLost,next.boss.currentLost);next.boss.weightLogs=Array.isArray(next.boss.weightLogs)?next.boss.weightLogs:[];next.boss.milestonesAwarded=Array.isArray(next.boss.milestonesAwarded)?next.boss.milestonesAwarded:[];next.weightLost=next.boss.bestLost;next.version=2;return next}catch{return clone(DEFAULT)}}
function save(){state.weightLost=state.boss.bestLost;localStorage.setItem('xusheng-state',JSON.stringify(state));schedulePush()}
// ===== 云同步层（Pages Functions + KV 绑定 XUSHENG_KV）=====
const SYNC_CODE_KEY='xusheng-sync-code',SYNC_STATUS_KEY='xusheng-sync-status';
const getSyncCode=()=>localStorage.getItem(SYNC_CODE_KEY)||'';
const setSyncCode=code=>code?localStorage.setItem(SYNC_CODE_KEY,code):localStorage.removeItem(SYNC_CODE_KEY);
let pushTimer=null;
function updateSyncIndicator(){const el=document.querySelector('#cloud-sync-status');if(!el)return;const code=getSyncCode();const map={synced:'已同步',syncing:'同步中…',offline:'离线·本地',error:'同步失败'};el.textContent=code?(map[localStorage.getItem(SYNC_STATUS_KEY)]||'已启用'):'未启用云同步';el.className='cloud-sync-status '+(code?('is-'+(localStorage.getItem(SYNC_STATUS_KEY)||'on')):'is-off')}
function setSyncStatus(s){localStorage.setItem(SYNC_STATUS_KEY,s);updateSyncIndicator()}
async function pushToCloud(){const code=getSyncCode();if(!code)return;const savedAt=Date.now();try{const res=await fetch('/api/state',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({code,state,savedAt})});setSyncStatus(res.ok?'synced':'error')}catch(e){setSyncStatus('offline')}}
function schedulePush(){if(!getSyncCode())return;setSyncStatus('syncing');clearTimeout(pushTimer);pushTimer=setTimeout(pushToCloud,800)}
async function pullFromCloud(){const code=getSyncCode();if(!code)return;setSyncStatus('syncing');try{const res=await fetch('/api/state?code='+encodeURIComponent(code));if(!res.ok){setSyncStatus('error');return}const data=await res.json();if(data&&data.state){localStorage.setItem('xusheng-state',JSON.stringify(data.state));state=loadState();render();setSyncStatus('synced');toast('已从云端同步')}else{pushToCloud();setSyncStatus('synced')}}catch(e){setSyncStatus('offline')}}
function activeTasks(){return state.tasks.filter(task=>task.active!==false)}
function todayDone(){return state.completed[dayKey()]||[]}
function level(){return Math.floor(state.totalXp/300)+1}
function xpInLevel(){return state.totalXp%300}
function taskXp(task){return XP_TIERS[task.tier]?.xp||20}
function titleForLevel(lv){if(lv>=10)return '序升主宰';if(lv>=5)return '稳定行者';if(lv>=3)return '见习序列者';return '初醒者'}
function svgCheck(){return '<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><path d="m5 12 4 4L19 6"/></svg>'}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function characterBlink(){if(motionReduced||characterBlinking)return;characterBlinking=true;const half=document.querySelector('.character-half-blink'),closed=document.querySelector('.character-closed-blink');half.classList.add('is-visible');await wait(95);half.classList.remove('is-visible');closed.classList.add('is-visible');await wait(120);closed.classList.remove('is-visible');half.classList.add('is-visible');await wait(105);half.classList.remove('is-visible');characterBlinking=false}
async function twitchCharacterEar(side=Math.random()<.5?'left':'right'){if(motionReduced)return;const ear=document.querySelector(`.character-ear-${side}`);ear.classList.remove('is-twitching');void ear.offsetWidth;ear.classList.add('is-twitching');await wait(380);ear.classList.remove('is-twitching')}
function characterReward(){const stage=document.querySelector('.character-stage');stage.classList.remove('is-rewarding');void stage.offsetWidth;stage.classList.add('is-rewarding');setTimeout(()=>stage.classList.remove('is-rewarding'),920);twitchCharacterEar();if(Math.random()<.28)characterBlink()}
async function characterIdleLoop(){while(!motionReduced){await wait(3500+Math.random()*4000);await characterBlink();if(Math.random()<.16){await wait(150+Math.random()*70);await characterBlink()}}}
async function characterEarLoop(){while(!motionReduced){await wait(4800+Math.random()*7000);await twitchCharacterEar()}}

function render(){renderHome();renderTasks();renderSide();renderAchievements();renderBoss();renderProfile()}
function renderHome(){const tasks=activeTasks(),done=todayDone().filter(id=>tasks.some(task=>task.id===id)),pct=tasks.length?Math.round(done.length/tasks.length*100):0,lv=level(),now=new Date(),weekday=new Intl.DateTimeFormat('en-US',{weekday:'short'}).format(now).toUpperCase();document.querySelector('#date-label').textContent=`${String(now.getMonth()+1).padStart(2,'0')}.${String(now.getDate()).padStart(2,'0')} / ${weekday}`;document.querySelector('#level-value').textContent=String(lv).padStart(2,'0');document.querySelector('#xp-value').textContent=`${xpInLevel()} / 300 XP`;document.querySelector('#today-percent').textContent=`${pct}%`;document.querySelector('#streak-value').textContent=state.streak;document.querySelector('#character-sync').textContent=`同步 ${pct}%`;document.querySelector('#core-progress').style.transform=`scaleX(${xpInLevel()/300})`;document.querySelector('#home-sync-fill').style.transform=`scaleY(${pct/100})`;const bossProgress=Math.min(15,state.boss.bestLost);const homeBossValue=document.querySelector('#home-boss-value'),homeBossFill=document.querySelector('#home-boss-fill');if(homeBossValue)homeBossValue.textContent=bossProgress.toFixed(1).replace('.0','');if(homeBossFill)homeBossFill.style.width=`${bossProgress/15*100}%`;const gains={strength:0,vitality:0,wisdom:0,charm:0};done.forEach(id=>{const task=state.tasks.find(item=>item.id===id);if(task)gains[task.attr]+=1});document.querySelector('#home-attributes').innerHTML=Object.entries(ATTRS).map(([key,a])=>`<div class="attribute-mini"><i></i><strong>+${gains[key]}</strong><span>${a.name}</span></div>`).join('');document.querySelector('#daily-note').textContent=tasks.length&&done.length===tasks.length?'全项同步完成。今天的角色状态已进入稳定增长。':done.length?`已完成 ${done.length} 项行动，还差 ${tasks.length-done.length} 项完成今日全勤。`:'完成第一项行动，启动今天的成长记录。'}
function taskMarkup(task,done,featured=false){const mark=escapeHtml(task.mark||ATTRS[task.attr].name.slice(0,1)),xp=taskXp(task);if(featured)return `<div class="task-row ${done?'is-done':''}"><button class="task-button" data-task-id="${task.id}" aria-pressed="${done}"><span class="task-icon">${done?svgCheck():mark}</span><span class="task-copy"><strong>${escapeHtml(task.title)}</strong><small>${escapeHtml(task.detail||XP_TIERS[task.tier].name)}</small></span><span class="task-cta">${done?'已完成':'开始记录'}</span></button></div>`;return `<div class="task-row ${done?'is-done':''}"><button class="task-button" data-task-id="${task.id}" aria-pressed="${done}"><span class="task-icon">${done?svgCheck():mark}</span><span class="task-copy"><strong>${escapeHtml(task.title)}</strong><small>${escapeHtml(task.detail||XP_TIERS[task.tier].name)}${task.boss?' · 讨伐支援':''}</small></span><span class="task-xp"><strong>${done?'已同步':`+${xp} XP`}</strong><small>${ATTRS[task.attr].name}</small></span></button><button class="task-edit" data-edit-task="${task.id}" aria-label="编辑${escapeHtml(task.title)}">•••</button></div>`}
function renderTasks(){const tasks=activeTasks(),done=todayDone(),doneCount=done.filter(id=>tasks.some(task=>task.id===id)).length;document.querySelector('#task-complete-count').textContent=doneCount;document.querySelector('#task-total-count').textContent=`/ ${tasks.length}`;document.querySelector('#mission-progress-bar').style.width=`${tasks.length?doneCount/tasks.length*100:0}%`;document.querySelector('#task-groups').innerHTML=tasks.length?['strength','vitality','charm'].map(attr=>{const list=tasks.filter(task=>task.attr===attr);if(!list.length)return'';const count=list.filter(task=>done.includes(task.id)).length;return `<section class="task-group"><div class="group-title"><strong>${GROUPS[attr]}</strong><span>${count} / ${list.length} 已同步</span></div>${list.map(task=>taskMarkup(task,done.includes(task.id))).join('')}</section>`}).join(''):`<div class="empty-state"><strong>主线档案为空</strong>点击右上角 +，添加你每天真正要做的行动。</div>`}
function renderSide(){const counts={reading:0,movie:0,learning:0};state.sideLogs.forEach(log=>counts[log.type]=(counts[log.type]||0)+1);document.querySelector('#side-categories').innerHTML=Object.entries(SIDE_META).map(([key,meta])=>`<div class="side-category"><i></i><strong>${counts[key]}</strong><span>${meta.name}</span></div>`).join('');document.querySelector('#side-count').textContent=`${state.sideLogs.length} 条探索`;document.querySelector('#side-log').innerHTML=state.sideLogs.length?state.sideLogs.slice().reverse().map(log=>`<article class="log-item"><i></i><div><strong>${escapeHtml(log.title)}</strong>${log.note?`<p>${escapeHtml(log.note)}</p>`:''}</div><time>${log.date.slice(5)}</time></article>`).join(''):`<div class="empty-state"><strong>探索区尚未写入</strong>完成一次阅读、观影或学习后，留下第一条记录。</div>`}
function completedCount(attr){return Object.values(state.completed).flat().filter(id=>state.tasks.find(task=>task.id===id)?.attr===attr).length}
function streakForTask(taskId){let streak=0,date=new Date();while((state.completed[dayKey(date)]||[]).includes(taskId)){streak++;date.setDate(date.getDate()-1)}return streak}
function achievements(){const tasks=activeTasks(),done=todayDone(),allThree=['strength','vitality','charm'].every(attr=>done.some(id=>tasks.find(task=>task.id===id)?.attr===attr)),maxTaskStreak=Math.max(0,...tasks.map(task=>streakForTask(task.id)));return[{name:'序列启动',desc:'完成第一项成长行动',value:Object.values(state.completed).flat().length,target:1,unit:'次'},{name:'七日校准',desc:'任一主线连续完成 7 天',value:maxTaskStreak,target:7,unit:'天'},{name:'二十一日稳态',desc:'任一主线连续完成 21 天',value:maxTaskStreak,target:21,unit:'天'},{name:'三十日长链',desc:'任一主线连续完成 30 天',value:maxTaskStreak,target:30,unit:'天'},{name:'力量成型',desc:'累计完成 30 次力量行动',value:completedCount('strength'),target:30,unit:'次'},{name:'全维同步',desc:'同一天完成力量、生命、魅力行动',value:allThree?1:0,target:1,unit:'次'},{name:'知识采样',desc:'累计记录 10 次阅读或学习',value:state.sideLogs.filter(log=>log.type!=='movie').length,target:10,unit:'条'},{name:'核心破译',desc:'突破 5 个减脂关卡',value:Math.floor(state.boss.bestLost),target:5,unit:'关'}]}
function renderAchievements(){const list=achievements(),earned=list.filter(item=>item.value>=item.target).length;document.querySelector('#badge-count').textContent=earned;const near=list.filter(item=>item.value<item.target).sort((a,b)=>b.value/b.target-a.value/a.target)[0]||list[list.length-1];document.querySelector('#featured-achievement').innerHTML=`<small>正在接近的成就</small><h2>${near.name}</h2><p>${near.desc} · ${Math.min(near.value,near.target)} / ${near.target}${near.unit}</p>`;document.querySelector('#achievement-list').innerHTML=list.map((item,index)=>`<div class="achievement-item ${item.value>=item.target?'is-earned':''}"><div class="badge-mark"><span>${String(index+1).padStart(2,'0')}</span></div><div class="achievement-copy"><strong>${item.name}</strong><small>${item.desc}</small><div class="tiny-track"><i style="width:${Math.min(100,item.value/item.target*100)}%"></i></div></div><div class="achievement-value">${Math.min(item.value,item.target)}/${item.target}</div></div>`).join('');const rewards=[{lv:3,text:'一顿喜欢的健康餐'},{lv:5,text:'一件提升生活的小物品'},{lv:10,text:'一次特别体验'}];document.querySelector('#reward-list').innerHTML=rewards.map(reward=>`<div class="reward-item ${level()>=reward.lv?'is-unlocked':''}"><div class="reward-node">LV${reward.lv}</div><div><strong>${reward.text}</strong><small>${level()>=reward.lv?'已解锁 · 记得为自己兑现':'继续积累行动经验'}</small></div></div>`).join('');const progress=Math.min(15,state.boss.bestLost);document.querySelector('#boss-entry-value').textContent=progress.toFixed(1).replace('.0','');document.querySelector('#boss-entry-fill').style.width=`${progress/15*100}%`}
function startOfWeek(){const date=new Date(),day=(date.getDay()+6)%7;date.setHours(0,0,0,0);date.setDate(date.getDate()-day);return date}
function bossShield(){const start=startOfWeek();let damage=0;Object.entries(state.completed).forEach(([date,ids])=>{if(new Date(`${date}T00:00:00`)<start)return;ids.forEach(id=>{const task=state.tasks.find(item=>item.id===id);if(task?.boss)damage+=({micro:2,standard:4,training:8,challenge:12}[task.tier]||4)})});return damage}
function renderBoss(){const boss=state.boss,current=Math.max(0,Math.min(15,Number(boss.currentLost)||0)),best=Math.max(0,Math.min(15,Number(boss.bestLost)||0)),remaining=Math.max(0,15-current),shield=bossShield();document.querySelector('#boss-remaining').textContent=remaining.toFixed(1);document.querySelector('#boss-hp-fill').style.width=`${current/15*100}%`;document.querySelector('#boss-best-label').textContent=`最佳 ${best.toFixed(1)} 斤`;document.querySelector('#boss-current-value').textContent=current.toFixed(1);document.querySelector('#boss-phase-label').textContent=best>=15?'讨伐完成 · 新阶段待命':best>=10?'第三阶段 · 核心击破':best>=5?'第二阶段 · 稳态推进':'第一阶段 · 启动';document.querySelector('#boss-shield-text').textContent=`${shield} / 60`;document.querySelector('#boss-shield-fill').style.width=`${Math.min(100,shield/60*100)}%`;document.querySelector('#boss-checkpoints').innerHTML=Array.from({length:15},(_,index)=>{const node=index+1;return `<div class="boss-node ${best>=node?'is-cleared':''} ${current<node&&best>=node?'is-held':''}"><span>${String(node).padStart(2,'0')}</span><small>${best>=node?'CLEARED':'LOCKED'}</small></div>`}).join('');document.querySelector('#boss-log').innerHTML=boss.weightLogs.length?boss.weightLogs.slice().reverse().slice(0,8).map(log=>`<div class="boss-log-item"><time>${log.date.slice(5)}</time><strong>${Number(log.value).toFixed(1)} 斤</strong><span>${log.xp?`+${log.xp} XP`:'趋势记录'}</span></div>`).join(''):`<div class="empty-state"><strong>尚未记录进度</strong>记录当前累计减脂，启动第一个讨伐节点。</div>`}
function renderProfile(){const lv=level();document.querySelector('#profile-level').textContent=`LV.${String(lv).padStart(2,'0')}`;document.querySelector('#profile-total-xp').textContent=`累计 ${state.totalXp} XP`;document.querySelector('#title-chip').textContent=titleForLevel(lv);document.querySelector('#profile-attributes').innerHTML=Object.entries(ATTRS).map(([key,attr])=>{const value=state.attributes[key]||0,step=value%20,progress=value&&step===0?100:step/20*100;return `<div class="profile-attribute-node attr-${key}"><span>${attr.name}</span><strong>${String(value).padStart(2,'0')}</strong><div class="profile-attribute-track"><i style="width:${progress}%"></i></div></div>`}).join('');document.querySelector('#weight-lost').textContent=Number(state.boss.bestLost).toFixed(1).replace('.0','');document.querySelector('#weight-progress').style.width=`${Math.min(100,state.boss.bestLost/15*100)}%`;const stats=[['主线完成',Object.values(state.completed).flat().length],['支线记录',state.sideLogs.length],['连续全勤',`${state.streak}天`]];document.querySelector('#stats-grid').innerHTML=stats.map(([name,value])=>`<div class="stat-cell"><strong>${value}</strong><span>${name}</span></div>`).join('')}
function calculateFullStreak(){let streak=0,date=new Date();while(true){const ids=state.completed[dayKey(date)]||[],tasks=activeTasks();if(!tasks.length||!tasks.every(task=>ids.includes(task.id)))break;streak++;date.setDate(date.getDate()-1)}return streak}
function toggleTask(id){const done=todayDone(),task=state.tasks.find(item=>item.id===id);if(!task||task.active===false)return;const oldLevel=level(),exists=done.includes(id),xp=taskXp(task);state.completed[dayKey()]=exists?done.filter(item=>item!==id):[...done,id];state.totalXp=Math.max(0,state.totalXp+(exists?-xp:xp));state.attributes[task.attr]=Math.max(0,(state.attributes[task.attr]||0)+(exists?-1:1));state.streak=calculateFullStreak();save();render();if(!exists){toast(`+${xp} XP · ${ATTRS[task.attr].name}提升`);characterReward();if(level()>oldLevel)showLevelUp()}}
function openTaskDialog(id){const task=id?state.tasks.find(item=>item.id===id):null;document.querySelector('#task-dialog-title').textContent=task?'编辑主线':'新增主线';document.querySelector('#task-id-input').value=task?.id||'';document.querySelector('#task-title-input').value=task?.title||'';document.querySelector('#task-detail-input').value=task?.detail||'';document.querySelector('#task-attr-input').value=task?.attr||'strength';document.querySelector('#task-tier-input').value=task?.tier||'standard';document.querySelector('#task-boss-input').checked=Boolean(task?.boss);document.querySelector('#task-disable').hidden=!task;document.querySelector('#task-dialog').showModal()}
function saveTaskFromForm(){const id=document.querySelector('#task-id-input').value,title=document.querySelector('#task-title-input').value.trim(),detail=document.querySelector('#task-detail-input').value.trim(),attr=document.querySelector('#task-attr-input').value,tier=document.querySelector('#task-tier-input').value,boss=document.querySelector('#task-boss-input').checked;if(!title)return;if(id){const task=state.tasks.find(item=>item.id===id);Object.assign(task,{title,detail,attr,tier,boss,mark:task.mark||ATTRS[attr].name.slice(0,1)})}else state.tasks.push({id:`task-${Date.now()}`,title,detail,attr,tier,boss,active:true,mark:ATTRS[attr].name.slice(0,1),createdAt:dayKey()});save();render();toast(id?'主线已更新':'新主线已写入档案')}
function disableCurrentTask(){const id=document.querySelector('#task-id-input').value,task=state.tasks.find(item=>item.id===id);if(!task)return;task.active=false;save();render();document.querySelector('#task-dialog').close();toast('任务已停用，历史记录保留')}
function weekLogCount(){const start=startOfWeek();return state.boss.weightLogs.filter(log=>new Date(`${log.date}T00:00:00`)>=start&&log.recordXp).length}
function recordBossProgress(){const value=Math.max(0,Math.min(15,Number(document.querySelector('#boss-record-input').value)||0)),boss=state.boss,oldBest=Number(boss.bestLost)||0,newBest=Math.max(oldBest,value),oldNode=Math.floor(oldBest),newNode=Math.floor(newBest);let xp=Math.max(0,newNode-oldNode)*50;[5,10,15].forEach(milestone=>{if(newBest>=milestone&&!boss.milestonesAwarded.includes(milestone)){xp+=({5:150,10:250,15:500})[milestone];boss.milestonesAwarded.push(milestone)}});const recordXp=weekLogCount()<3?5:0;xp+=recordXp;boss.currentLost=value;boss.bestLost=newBest;boss.weightLogs.push({date:dayKey(),value,xp,recordXp:Boolean(recordXp)});state.totalXp+=xp;save();render();toast(xp?`讨伐进度已记录 · +${xp} XP`:'讨伐趋势已记录');if(newBest>oldBest)characterReward()}
function syncCharacterVideos(page=currentPage){const videos=[['home-character-video','home'],['profile-character-video','profile']];videos.forEach(([id,targetPage])=>{const video=document.querySelector(`#${id}`);if(!video)return;const shouldPlay=!motionReduced&&!document.hidden&&page===targetPage;if(shouldPlay)video.play().catch(()=>{});else video.pause()})}
function switchPage(page){currentPage=page;document.body.className=page==='home'?'page-home':`page-archive-system page-${page}`;document.querySelectorAll('.page').forEach(section=>section.classList.toggle('is-active',section.dataset.page===page));document.querySelectorAll('.bottom-nav button').forEach(button=>button.classList.toggle('is-active',button.dataset.pageTarget===(page==='boss'?'achievements':page)));document.querySelector('#header-title').textContent={home:'行动面板',main:'主线协议',side:'自由探索',achievements:'成就档案',boss:'目标讨伐',profile:'角色信息'}[page];syncCharacterVideos(page);window.scrollTo({top:0,behavior:motionReduced?'auto':'smooth'})}
function toast(message){const node=document.querySelector('#xp-toast');node.textContent=message;node.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('show'),2200)}
function showLevelUp(){document.querySelector('#new-level').textContent=String(level()).padStart(2,'0');const node=document.querySelector('#level-up');node.classList.add('show');setTimeout(()=>node.classList.remove('show'),1900)}

document.addEventListener('click',event=>{const nav=event.target.closest('[data-page-target]');if(nav)switchPage(nav.dataset.pageTarget);const task=event.target.closest('[data-task-id]');if(task)toggleTask(task.dataset.taskId);const edit=event.target.closest('[data-edit-task]');if(edit)openTaskDialog(edit.dataset.editTask)});
document.querySelector('#open-task-form').addEventListener('click',()=>openTaskDialog());document.querySelector('#task-form').addEventListener('submit',saveTaskFromForm);document.querySelector('#task-disable').addEventListener('click',disableCurrentTask);
document.querySelector('#open-side-form').addEventListener('click',()=>document.querySelector('#side-dialog').showModal());document.querySelector('#side-form').addEventListener('submit',()=>{const title=document.querySelector('#side-title-input').value.trim();if(!title)return;state.sideLogs.push({type:document.querySelector('#side-type').value,title,note:document.querySelector('#side-note-input').value.trim(),date:dayKey()});state.totalXp+=25;state.attributes.wisdom+=1;save();render();document.querySelector('#side-form').reset();toast('+25 XP · 智慧提升')});
document.querySelector('#open-boss').addEventListener('click',()=>switchPage('boss'));document.querySelector('#home-boss-entry')?.addEventListener('click',()=>switchPage('boss'));document.querySelector('#close-boss').addEventListener('click',()=>switchPage('achievements'));document.querySelector('#open-boss-record').addEventListener('click',()=>{document.querySelector('#boss-record-input').value=state.boss.currentLost;document.querySelector('#boss-record-dialog').showModal()});document.querySelector('#boss-record-form').addEventListener('submit',recordBossProgress);
document.querySelector('#edit-weight').addEventListener('click',()=>switchPage('boss'));
function exportData(){const data=localStorage.getItem('xusheng-state');if(!data){toast('没有可备份的数据');return}const blob=new Blob([data],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`xusheng-backup-${dayKey()}.json`;a.click();URL.revokeObjectURL(url);toast('备份已导出，请存入云盘')}
function importData(event){const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(String(reader.result));localStorage.setItem('xusheng-state',JSON.stringify(parsed));state=loadState();save();render();toast('备份已恢复')}catch{toast('备份文件无效')}};reader.readAsText(file);event.target.value=''}
document.querySelector('#export-data').addEventListener('click',exportData);document.querySelector('#import-data').addEventListener('click',()=>document.querySelector('#import-file').click());document.querySelector('#import-file').addEventListener('change',importData);document.querySelector('#weight-dialog').remove();document.querySelector('#monthly-report').addEventListener('click',()=>toast('月度报告将在下一阶段开放'));document.querySelector('#reset-data').addEventListener('click',()=>{if(confirm('确认清除所有本地记录？此操作无法撤销。')){state=clone(DEFAULT);save();render();toast('本地记录已重置')}});
document.querySelector('#sync-enable').addEventListener('click',()=>{const code=document.querySelector('#sync-code-input').value.trim();if(!code){toast('请输入同步码');return}setSyncCode(code);document.querySelector('#sync-code-input').value=code;pullFromCloud();toast('云同步已启用')});
document.querySelector('#sync-disable').addEventListener('click',()=>{setSyncCode('');updateSyncIndicator();toast('已断开云同步')});
document.querySelector('.character-stage').addEventListener('pointerdown',()=>{twitchCharacterEar();if(Math.random()<.16)characterBlink()});if('serviceWorker'in navigator){let refreshing=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(refreshing)return;refreshing=true;location.reload()});window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(registration=>registration.update()))}
document.addEventListener('visibilitychange',()=>syncCharacterVideos());
render();syncCharacterVideos();const _sc=getSyncCode();if(_sc)document.querySelector('#sync-code-input').value=_sc;updateSyncIndicator();if(_sc)pullFromCloud();document.querySelector('#boot')?.classList.add('is-hidden');characterIdleLoop();characterEarLoop();
